apiVersion: v1
kind: ConfigMap
metadata:
  name: nacritan-backend-nginx
  labels:
    tier: nacritan-backend
data:
  config : |

    log_format nacritan '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $ssl_protocol "$http_Authorization"';

    server {
      listen      80;
      server_name <URL>;
      access_log  /var/log/nginx/access.log nacritan;

      location /.well-known/acme-challenge/ {
          root /var/www/certbot;
      }

      location / {
        proxy_pass          http://<SERVICE>:5000;
        proxy_http_version  1.1;
        proxy_buffers       16 16k;
        proxy_buffer_size   16k;
      }
    }

    server {
      listen 443 ssl;
      server_name <URL>;
      access_log  /var/log/nginx/access.log nacritan;

      add_header          Strict-Transport-Security 'max-age=63072000; includeSubDomains; preload;' always;

      ssl_session_cache   shared:SSL:10m;
      ssl_session_timeout 1440m;
      ssl_session_tickets off;

      ssl_protocols       TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers on;
      ssl_ciphers         ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;

      ssl_certificate     /etc/letsencrypt/live/<URL>/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/<URL>/privkey.pem;

      location / {
        proxy_pass          http://<SERVICE>:5000;
        proxy_http_version  1.1;
        proxy_buffers       16 16k;
        proxy_buffer_size   16k;
      }
    }
