apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacritan-backend-api
  labels:
    tier: nacritan-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: nacritan-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        tier: nacritan-backend
    spec:

      initContainers:
      - name: nacritan-backend-api-init
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/nacridan-retriever-backend/archive/master.zip -O /tmp/nrb.zip &&
              unzip  /tmp/nrb.zip -d /tmp/ &&
              cp -a  /tmp/nacridan-retriever-backend-master/python/* /code/ &&
              rm -rf /tmp/nacridan-retriever-backend-master &&
              rm -rf /tmp/nrb.zip
          ) || echo 1"
        ]

      containers:
      - name: nacritan-backend-api
        image: alpine
        command: ["/code/entrypoint.sh"]
        env:
        - name: FLASK_DEBUG
          value: '--debugger'
        - name: FLASK_THREAD
          value: '--without-threads'
        - name: SQLITE_DB_NAME
          value: /db/nacridan.db
        - name: FLASK_ENV
          value: 'development'
        - name: FLASK_APP
          value: '/code/app.py'
        - name: FLASK_HOST
          value: '0.0.0.0'
        - name: FLASK_PORT
          value: '5000'
        - name: AUTH_TOKENS
          value: "{'TOKEN1': 'user1','TOKEN2': 'user2'}"
        - name: REDIS_HOST
          value: 'nacritan-backend-redis-svc'
        volumeMounts:
        - mountPath: /code
          name: code
        - mountPath: /db
          name: db
      restartPolicy: Always

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: nacritan-backend-code-api
      - name: db
        persistentVolumeClaim:
          claimName: nacritan-sqlite-db
